# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for Postgres to be ready
        run: |
          sudo apt-get update && sudo apt-get install -y netcat
          for i in {1..30}; do
            nc -z localhost 5432 && echo "✅ Postgres is up" && break
            echo "⏳ Waiting for Postgres..."
            sleep 1
          done

      - name: Apply migrations
        run: python manage.py migrate

      - name: Run backend tests
        run: pytest -q

      - name: Generate snapshot
        run: python snapshot_generator.py

      - name: Generate changelog
        run: python manage.py changelog > changelog.txt

      - name: Build Docker image
        run: docker build -t lifehub-backend .

      - name: Upload snapshot & changelog
        uses: actions/upload-artifact@v3
        with:
          name: project-artifacts
          path: |
            snapshots/*.json
            changelog.txt

  frontend:
    runs-on: ubuntu-latest
    needs: backend
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd lifehub-ui
          npm ci

      - name: Run frontend tests
        run: |
          cd lifehub-ui
          npm test -- --watchAll=false

      - name: Build frontend
        run: |
          cd lifehub-ui
          npm run build

      - name: Upload frontend build
        uses: actions/upload-artifact@v3
        with:
          name: frontend-dist
          path: lifehub-ui/dist
