# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Wait for Postgres
        run: |
          sudo apt-get update
          sudo apt-get install -y netcat
          until nc -z localhost 5432; do
            echo "⏳ Čekám na Postgres…"
            sleep 1
          done
      - name: Apply migrations
        run: python manage.py migrate
      - name: Run tests & snapshot
        run: |
          pytest -q
          python snapshot_generator.py
      - name: Build Docker image
        run: docker build -t lifehub-backend .

  frontend:
    runs-on: ubuntu-latest
    needs: backend
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install & test
        run: |
          cd lifehub-ui
          npm ci
          npm test -- --watchAll=false
      - name: Build
        run: |
          cd lifehub-ui
          npm run build
